# Generated by Django 4.2.6 on 2023-11-12 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=255)),
                ('a_date', models.DateTimeField(auto_now_add=True)),
                ('a_location', models.CharField(blank=True, default='', max_length=255)),
                ('a_text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_date', models.DateTimeField(auto_now_add=True)),
                ('p_url', models.CharField(max_length=255)),
                ('p_hit', models.IntegerField(default=0)),
                ('p_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
    ]
