# Generated by Django 4.2.6 on 2023-10-25 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comtent',
            new_name='content',
        ),
    ]
