# Generated by Django 4.2.6 on 2023-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_comment', '0008_profilecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecard',
            name='selfinfo',
            field=models.TextField(),
        ),
    ]
