# Generated by Django 4.2.6 on 2023-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_comment', '0009_alter_profilecard_selfinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecard',
            name='fb_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='ig_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilecard',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
